Fix sign in redirect
likecoin/lunie-ng pull request #11
Opened 2022-02-18 14:36 UTC by nwingt

2022-02-18 17:35 UTC, williamchong requested changes

2022-02-18 17:35 UTC, williamchong commented on components/Modal/Stake.vue
> +    :target-validator="targetValidator.id"
Is this still used?

2022-02-19 06:44 UTC, williamchong approved these changes

2022-02-19 12:11 UTC, AuroraHuang22 approved these changes

2022-02-21 02:55 UTC, merged