:recycle: Check login/send address :like & cosmos
likecoin/lunie-ng pull request #29
Opened 2022-04-28 02:09 UTC by Tsai-Hsueh-Kuan

The original method will limit only one prefix, change to permission both prefix

2022-04-28 07:40 UTC, williamchong requested changes
In this case, change `this.network.addressPrefix` into `this.network.addressPrefixes = []` in config would be better than hardcoding prefix

2022-04-28 12:03 UTC, Tsai-Hsueh-Kuan commented
> In this case, change `this.network.addressPrefix` into `this.network.addressPrefixes = []` in config would be better than hardcoding prefix

ok! but network.addressPrefix use it in many places. If I change it, I still need the 'like' prefix in other places: network.addressPrefix[0], is that better for you?
![image](https://user-images.githubusercontent.com/77050332/165747899-83e2001e-6e8b-4f12-90dd-17538c62a898.png)

2022-05-01 20:06 UTC, williamchong requested changes

2022-05-01 20:06 UTC, williamchong commented on components/Modal/Send.vue
> +        }
I think simpler would be `address  && this.network.allowedAddressPrefix.some(prefix => address.startsWith(prefix))`

2022-05-01 20:48 UTC, merged