Feature/fix tx send receive
likecoin/lunie-ng pull request #30
Opened 2022-05-05 07:43 UTC by Tsai-Hsueh-Kuan

Feature/fix tx send receive

2022-05-05 10:30 UTC, williamchong approved these changes

2022-05-05 10:36 UTC, WeiJun0827 approved these changes

2022-05-06 04:14 UTC, WeiJun0827 approved these changes
Looks good to me. By the way, I found a similar pattern [here](https://github.com/likecoin/lunie-ng/blob/likecoin/store/data.js#L218-L229) for reference. Not sure if it's necessary to be modified in this PR.

2022-05-06 13:27 UTC, williamchong requested changes

2022-05-06 13:27 UTC, williamchong commented on common/address.js
> -  isValidCosmosAddress(address) {
are these isValidXXXAddress used anywhere now? If not please remove

2022-05-07 03:05 UTC, williamchong approved these changes

2022-05-07 03:05 UTC, williamchong commented
conflict though

2022-05-07 03:21 UTC, WeiJun0827 approved these changes

2022-05-09 02:47 UTC, merged