💄 Display NFT Tx messages related to user's wallet only
likecoin/lunie-ng pull request #40
Opened 2022-09-29 12:18 UTC by WeiJun0827

Before:
<img width="1512" alt="截圖 2022-09-29 下午8 13 02" src="https://user-images.githubusercontent.com/33746295/193028644-91cfcb21-f440-4b90-825d-202b178b153d.png">

<img width="1512" alt="截圖 2022-09-29 下午8 13 21" src="https://user-images.githubusercontent.com/33746295/193028665-297922f9-8ded-4bee-9537-9bdbca147d26.png">

After:
<img width="1512" alt="截圖 2022-09-29 下午8 12 37" src="https://user-images.githubusercontent.com/33746295/193028820-c16dc6e9-b490-4f48-9526-90d1257a2517.png">

2022-09-30 05:59 UTC, nwingt commented on apis/cosmos-reducers.js
> +      return lunieMessageTypes.COLLECT_NFT;
`cosmos.authz.v1beta1.MsgExec` might come from https://restake.app

2022-09-30 05:59 UTC, nwingt commented on components/transactions/TransactionItem.vue
> +    classId() {
`classId` seems too generic
```suggestion
    nftClassId() {
```

2022-09-30 05:59 UTC, nwingt commented on apis/cosmos-reducers.js
> +    classId: message.class_id,
```suggestion
    nftClassId: message.class_id,
```

2022-09-30 05:59 UTC, nwingt commented on apis/cosmos-reducers.js
> +    classId: message.class_id,
```suggestion
    nftClassId: message.class_id,
```

2022-10-03 02:36 UTC, nwingt commented on components/transactions/TransactionItem.vue
> +            return ``
How about `Grant`?

2022-10-03 09:02 UTC, williamchong requested changes

2022-10-03 09:02 UTC, williamchong commented on components/transactions/TransactionItem.vue
> +            this.transaction.details.grantee === LIKECOIN_NFT_API_WALLET
I think we should just show `Grant` here as this is chain explorer, and avoid introducing `LIKECOIN_NFT_API_WALLET` here.
Also having a Grant tx passed does not necessarily means a NFT is sucessfully collected, it can fail, so this might be misleading.

2022-10-05 04:35 UTC, williamchong approved these changes

2022-10-05 05:33 UTC, merged